Add option to continue despite koji failures

diff --git a/release-koji b/release-koji
--- a/release-koji
+++ b/release-koji
@@ -20,6 +20,8 @@
 #
 # -f tgz     RELEASE_TARBALL=tbz    The tarball to upload
 #                                   default: no file attachment
+# -k         RELEASE_CONTINUE=1     Ignore build failure and skip the
+#                                   branch without failing delivery.
 # -p package RELEASE_PACKAGE=name   The distgit name of the package
 # -t 0.X     RELEASE_TAG=0.X        The tag to create release from
 #                                   default: latest tag
@@ -41,6 +43,7 @@ TRANSACTION=${RELEASE_TRANSACTION:-0}
 QUIET=${RELEASE_QUIET:-0}
 VERBOSE=${RELEASE_VERBOSE:-0}
 TARBALL=${RELEASE_TARBALL:-}
+CONTINUE=${RELEASE_CONTINUE:-0}
 SPEC=${RELEASE_SPEC:-$PACKAGE.spec}
 
 # Other globals
@@ -51,7 +54,7 @@ BRANCH=""
 
 usage()
 {
-    echo "usage: release-koji [-qvx] [-t TAG] [-s SPEC] [-f TARBALL] [-p PACKAGE] BRANCH" >&2
+    echo "usage: release-koji [-kqvx] [-t TAG] [-s SPEC] [-f TARBALL] [-p PACKAGE] BRANCH" >&2
     exit ${1-2}
 }
 
@@ -114,7 +117,7 @@ readlink_or()
 
 prepare()
 {
-    local spec tmpfile srpm tarball
+    local spec tmpfile srpm tarball ret
 
     WORKDIR="koji-$BRANCH"
 
@@ -163,15 +166,18 @@ prepare()
     trace "Building SRPM"
 
     # Make an SRPM out of that
-    tmpfile=$(mktemp .fedpkg-srpm.XXXXXX)
-    srpm=$(cd $WORKDIR && fedpkg srpm | sed -n 's/Wrote: \(.\+\.src\.rpm\)$/\1/p')
+    cd $WORKDIR
+    srpm=$(fedpkg srpm | sed -n 's/Wrote: \(.\+\.src\.rpm\)$/\1/p')
 
     trace "Making a scratch build"
 
     # Build it in brew
-    (cd $WORKDIR && fedpkg scratch-build --srpm=$srpm)
-
-    CLEANUP="$CLEANUP $tmpfile"
+    if ! fedpkg scratch-build --srpm=$srpm; then
+        ret=$?
+        if [ $CONTINUE -eq 0 ]; then
+            exit $ret
+        fi
+    fi
 }
 
 commit()
@@ -188,10 +194,13 @@ commit()
     fedpkg build
 )
 
-while getopts "f:p:s:t:qvx" opt; do
+while getopts "f:kp:s:t:qvx" opt; do
     case "$opt" in
     f)
         TARBALL="$OPTARG"
+        ;;
+    k)
+        CONTINUE=1
         ;;
     p)
         PACKAGE="$OPTARG"
