tasks: Introduce elastic cloud runner mode
Let the cockpit-tasks main runner keep track of whether `run-queue` ever
succeeded (i.e. picked something from the queue and ran it), and
otherwise exit with 100. Tell the systemd unit that 100 is a successful
exit code, to avoid confusing log noise.

Let all cockpit-tasks@*.service run in a specific (instead of the
automatic anonymous) `idle-poweroff.slice`, so that we can react to all
tasks containers shutting down.

When calling the installation script with `$IDLE_POWEROFF`, configure
the slice to automatically power off the machine once all cockpit-tasks
instances exited cleanly (we don't want this on failures, so that we can
ssh in and examine them). Use the `poweroff-immediate` heavy hammer
there, to avoid potential hangs on shutdown -- there is nothing to
rescue from the instance anyway.

Plumb that through the AWS Ansible role and document it.

diff --git a/tasks/cockpit-tasks b/tasks/cockpit-tasks
--- a/tasks/cockpit-tasks
+++ b/tasks/cockpit-tasks
@@ -62,6 +62,8 @@ function slumber() {
 # on mass deployment, avoid GitHub stampede
 slumber 0-120
 
+work_done=
+
 # Consume from queue 30 times, then restart; listen to SIGTERM for orderly shutdown
 shutdown=
 trap "echo 'received SIGTERM, stopping main loop'; shutdown=1" TERM
@@ -76,8 +78,12 @@ for i in $(seq 1 30); do
     pkill -9 virtqemud || true
     while pgrep virtqemud >/dev/null; do sleep 0.5; done
 
-    # run-queue fails on empty queues; don't poll too often
-    timeout 12h ./run-queue ${AMQP_SERVER:+--amqp} ${AMQP_SERVER:-} || slumber
+    if timeout 12h ./run-queue ${AMQP_SERVER:+--amqp} ${AMQP_SERVER:-}; then
+       work_done=1
+    else
+        # run-queue fails on empty queues; don't poll too often
+        slumber
+    fi
     # clean up after tests, in particular large qcow overlays
     rm -rf /tmp/* || true
 done
@@ -90,3 +96,6 @@ update_bots
 for region in eu-central-1 us-east-1; do
     ./image-prune --s3 "https://cockpit-images.${region}.linodeobjects.com/" || true
 done
+
+# no work done at all? signal that to our systemd unit
+[ -n "$work_done" ] || exit 100
